---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workspace
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./workspaces/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: workspace

