---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requiredserviceaccountname
  annotations:
    description: >-
      Requires the given resource to have the
      .spec.serviceAccountName field set.
spec:
  crd:
    spec:
      names:
        kind: RequiredServiceAccountName
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiredserviceaccountname

        violation[{"msg": msg}] {
          value := object.get(input.review.object.spec, "serviceAccountName", "")
          value == ""
          msg := "must have a serviceAccountName set"
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredServiceAccountName
metadata:
  name: helmrelease-must-have-sa
spec:
  match:
    kinds:
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        kinds: ["HelmRelease"]
    excludedNamespaces: ["flux-system"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredServiceAccountName
metadata:
  name: kustomization-must-have-sa
spec:
  match:
    kinds:
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        kinds: ["Kustomization"]
    excludedNamespaces: ["flux-system"]
